"""Download GeoNames dumps and generate city/country database modules for geofind."""

import json
import shutil
import zipfile
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen

DEV_DIR = Path(__file__).resolve().parent
TMP_DIR = DEV_DIR / "tmp"
OUT_DIR = DEV_DIR.parent / "geofind" / "utils"

CITIES_URL = "http://download.geonames.org/export/dump/cities15000.zip"
COUNTRIES_URL = "http://download.geonames.org/export/dump/countryInfo.txt"

MIN_POPULATION = 100_000


def download(url: str, dest: Path) -> None:
    print(f"    GET {url}")
    req = Request(url, headers={"User-Agent": "Mozilla/5.0 (geofind-setup)"})
    try:
        with urlopen(req, timeout=120) as resp, open(dest, "wb") as out:
            total = int(resp.headers.get("Content-Length") or 0)
            done = 0
            while True:
                chunk = resp.read(1 << 16)
                if not chunk:
                    break
                out.write(chunk)
                done += len(chunk)
                if total:
                    pct = done * 100 // total
                    print(f"\r    {done / 1e6:7.2f} / {total / 1e6:.2f} MB ({pct}%)", end="", flush=True)
        print()
    except URLError as exc:
        raise SystemExit(f"ERROR: download failed: {exc}") from exc


def sanitize_key(name: str) -> str:
    return "_".join(name.strip().lower().split())


def valid_coords(lat: float, lon: float) -> bool:
    return -90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0 and not (lat == 0.0 and lon == 0.0)


def parse_rows(path: Path) -> tuple[list[dict], int]:
    rows: list[dict] = []
    skipped = 0
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\r\n")
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) < 15:
                skipped += 1
                continue
            try:
                lat = float(parts[4])
                lon = float(parts[5])
            except ValueError:
                skipped += 1
                continue
            try:
                population = int(parts[14])
            except ValueError:
                population = 0
            rows.append(
                {
                    "name": parts[2],
                    "lat": round(lat, 4),
                    "lon": round(lon, 4),
                    "feature_code": parts[7],
                    "country": parts[8],
                    "population": population,
                }
            )
    return rows, skipped


def build_city_db(filtered: list[dict]) -> dict[str, dict]:
    best: dict[tuple[str, str], dict] = {}
    for rec in filtered:
        key = (rec["name"], rec["country"])
        cur = best.get(key)
        if cur is None or rec["population"] > cur["population"]:
            best[key] = rec

    city_db: dict[str, dict] = {}
    for rec in best.values():
        key = sanitize_key(rec["name"])
        cur = city_db.get(key)
        if cur is None or rec["population"] > cur["population"]:
            city_db[key] = rec
    return city_db


def build_countries(path: Path, places: list[dict]) -> dict[str, dict]:
    by_country: dict[str, list[dict]] = {}
    capital_lookup: dict[tuple[str, str], dict] = {}
    for rec in places:
        by_country.setdefault(rec["country"], []).append(rec)
        ck = (sanitize_key(rec["name"]), rec["country"])
        cur = capital_lookup.get(ck)
        if cur is None or rec["population"] > cur["population"]:
            capital_lookup[ck] = rec

    result: dict[str, dict] = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 6:
                continue
            iso, name, capital = parts[0], parts[4], parts[5]
            cap_rec = capital_lookup.get((sanitize_key(capital), iso))
            if cap_rec is not None:
                lat, lon = cap_rec["lat"], cap_rec["lon"]
            else:
                plist = by_country.get(iso)
                if plist:
                    lat = round(sum(p["lat"] for p in plist) / len(plist), 4)
                    lon = round(sum(p["lon"] for p in plist) / len(plist), 4)
                else:
                    lat = lon = None
            result[iso] = {"name": name, "lat": lat, "lon": lon, "capital": capital}
    return result


def py_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_city_module(path: Path, db: dict[str, dict]) -> None:
    lines = [
        "# Auto-generated from GeoNames database (cities with population >= 100,000)",
        "# Generated by dev/setup_city_db.py",
        '# Format: city_name: {"lat": float, "lon": float, "country": str, "population": int}',
        "",
        "CITY_DATABASE: dict[str, dict] = {",
    ]
    for key in sorted(db):
        rec = db[key]
        lines.append(
            f'    {py_str(key)}: {{"lat": {rec["lat"]}, "lon": {rec["lon"]}, '
            f'"country": {py_str(rec["country"])}, "population": {rec["population"]}}},'
        )
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_country_module(path: Path, db: dict[str, dict]) -> None:
    lines = [
        "# Auto-generated from GeoNames country data",
        "# Generated by dev/setup_city_db.py",
        "",
        "COUNTRY_DATABASE: dict[str, dict] = {",
    ]
    for iso in sorted(db):
        rec = db[iso]
        lines.append(
            f'    {py_str(iso)}: {{"name": {py_str(rec["name"])}, "lat": {rec["lat"]}, '
            f'"lon": {rec["lon"]}, "capital": {py_str(rec["capital"])}}},'
        )
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def print_stats(city_db: dict[str, dict], country_db: dict[str, dict], pre_dedup: int) -> None:
    print()
    print("=" * 56)
    print("STATISTICS")
    print("=" * 56)
    print(f"Cities matching filters (pre-dedup): {pre_dedup:>7,}")
    print(f"Unique cities in database          : {len(city_db):>7,}")
    print(f"Countries in database              : {len(country_db):>7,}")
    print()
    print("Top 20 cities by population:")
    top = sorted(city_db.values(), key=lambda r: r["population"], reverse=True)[:20]
    for i, rec in enumerate(top, 1):
        print(f"  {i:>2}. {rec['name']:<28} {rec['country']}  {rec['population']:>13,}")
    print()


def main() -> None:
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    try:
        print("[1/6] Downloading cities15000.zip ...")
        cities_zip = TMP_DIR / "cities15000.zip"
        download(CITIES_URL, cities_zip)

        print("[2/6] Extracting cities15000.zip ...")
        with zipfile.ZipFile(cities_zip) as zf:
            zf.extractall(TMP_DIR)
        cities_txt = TMP_DIR / "cities15000.txt"
        if not cities_txt.exists():
            raise SystemExit("ERROR: cities15000.txt not found after extraction")

        print("[3/6] Downloading countryInfo.txt ...")
        countries_txt = TMP_DIR / "countryInfo.txt"
        download(COUNTRIES_URL, countries_txt)

        print("[4/6] Parsing and filtering cities ...")
        rows, skipped = parse_rows(cities_txt)
        print(f"    parsed {len(rows):,} rows ({skipped} malformed lines skipped)")
        all_p = [r for r in rows if r["feature_code"].startswith("P") and valid_coords(r["lat"], r["lon"])]
        filtered = [r for r in all_p if r["population"] >= MIN_POPULATION]
        print(f"    populated places (P*): {len(all_p):,}")
        print(f"    with population >= {MIN_POPULATION:,}: {len(filtered):,}")
        city_db = build_city_db(filtered)
        print(f"    after dedup by (name, country): {len(city_db):,}")

        print("[5/6] Building country data ...")
        country_db = build_countries(countries_txt, all_p)
        print(f"    countries: {len(country_db):,}")

        print("[6/6] Writing output modules ...")
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        write_city_module(OUT_DIR / "city_database.py", city_db)
        write_country_module(OUT_DIR / "country_database.py", country_db)
        print(f"    wrote {OUT_DIR / 'city_database.py'}")
        print(f"    wrote {OUT_DIR / 'country_database.py'}")

        print_stats(city_db, country_db, len(filtered))
    finally:
        shutil.rmtree(TMP_DIR, ignore_errors=True)
        print("Temp dir cleaned up.")


if __name__ == "__main__":
    main()
